/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const mcp_jsonrpc: (a: number, b: number) => [number, number];
export const version: () => [number, number];
export const __wbg_federatednodemanager_free: (a: number, b: number) => void;
export const __wbg_get_wasmoffloadintent_opcode: (a: number) => number;
export const __wbg_get_wasmoffloadintent_payload_size: (a: number) => number;
export const __wbg_get_wasmoffloadintent_priority: (a: number) => number;
export const __wbg_set_wasmoffloadintent_opcode: (a: number, b: number) => void;
export const __wbg_set_wasmoffloadintent_payload_size: (a: number, b: number) => void;
export const __wbg_set_wasmoffloadintent_priority: (a: number, b: number) => void;
export const __wbg_wasmoffloadintent_free: (a: number, b: number) => void;
export const enforce_rights_ontology: (a: bigint) => number;
export const federatednodemanager_discover_capabilities: (a: number) => number;
export const federatednodemanager_new: () => number;
export const federatednodemanager_offload_intent: (a: number, b: number) => [number, number, number, number];
export const intercept_computational_opcode: (a: number, b: number) => number;
export const intercept_pharmacogenomics_intent: (a: number, b: number) => number;
export const serialize_float64_array: (a: number, b: number) => any;
export const serialize_float_array: (a: number, b: number) => any;
export const wasmoffloadintent_new: (a: number, b: number, c: number) => number;
export const wasmoffloadintent_with_string_payload: (a: number, b: number, c: number, d: number) => number;
export const webizen_poll_agreements: () => [number, number];
export const webizen_propose_agreement: (a: any, b: number, c: number, d: number, e: number, f: number) => bigint;
export const webizen_sign_agreement: (a: bigint, b: number, c: number) => void;
export const prune_and_validate_mesh: (a: bigint) => number;
export const estimate_browser_storage: () => any;
export const is_opfs_block_cached: (a: number) => any;
export const pack_quins_into_superblock: (a: bigint, b: bigint, c: number, d: number) => [number, number, number];
export const read_opfs_block: (a: number) => any;
export const verify_superblock_ecc: (a: number, b: number) => [number, number];
export const write_opfs_block: (a: number, b: number, c: number) => any;
export const wasm_bindgen__convert__closures_____invoke__h8803f8c799f93ab4: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h243b5e59773a58aa: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
